function setupMapTime () {
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    statusbars.getStatusBarAttachedTo(StatusBarKind.Energy, playerSprite).value += 200
    if (isDaytime) {
        tiles.setCurrentTilemap(tilemap`level2`)
        if (Math.percentChance(100)) {
            moonky = sprites.create(img`
                ..................................................
                ..................................................
                ..................................................
                ..................................................
                ..................................................
                ..................................................
                ..................................................
                ..................................................
                ..................................................
                ..................................................
                ..................................................
                ..................................................
                ..................................................
                ..................................................
                ..................................................
                ..................................................
                ..................................................
                ..................................................
                .........11dddd...................................
                ......111111111d..................................
                ......1111111111d.................................
                ......1fff111111d.................................
                ......1fff1ff111d.................................
                ......1f2d1fff111.................................
                ......1ffd1d2f111.................................
                ......1df11dff111.................................
                ......11d111dd111.................................
                .......111fff1111.................................
                .......1fffff1111.................................
                .......1ffffd11111................................
                .......1ffff11d1111...............................
                .......1fff1d111d1111..1dddd1111..................
                .......12ffdd111dd1d111111ddd1111111d.............
                ........22dd.11111d11111111ddd1111111d............
                ........12d..1111111111111111111111111d...........
                ........112..11111111111111d1111d111111...........
                .............1111111111d111dd111d111111...........
                .............1111111111d1111d111d11111d...........
                ............dd111111111d1111d111dd1111d...........
                ...........dd111d111111d111dd1111d1111d...........
                ..........1d1111.d1111dd111d1111dd1111d...........
                .........111111....1111111111111d111111d..........
                .........12111.....1211...11111111111111d.........
                ........11121......211d......1d1111111111d........
                ........1211.......112.........d21...d11211.......
                ........2222.......22d.........d12....d2112.......
                ........222........d2d.........22d.....d122.......
                ...............................22d......dd2.......
                ..................................................
                ..................................................
                `, SpriteKind.Enemy)
            tiles.placeOnRandomTile(moonky, assets.tile`myTile1`)
            moonky.follow(playerSprite, 75)
        }
        info.changeScoreBy(1)
    } else {
        tiles.setCurrentTilemap(tilemap`level1`)
        if (Math.percentChance(100)) {
            snake = sprites.create(img`
                ..................................................
                ..................................................
                ..................................................
                ..................................................
                ..................................................
                ...........................fff....................
                ........................ffffff....................
                ......................fffffffff...................
                .....................ffffffffff...................
                ....................ffffffddcfff..................
                ....................fffddcdcdfff..................
                ....................fffcdcccbbfff.................
                ....................fffdccccddfff.................
                ....................fffbbddccdfff.................
                ....................fffffbddccff..................
                .....................ffffffffff...................
                ......................fffffffff...................
                ........................ffffff....................
                .........................d212.....................
                .........................b2d......................
                ..........................2.......................
                .........................12b......................
                .........................2.d......................
                ........................2b.2......................
                ........................2b.2b.....................
                ......................ffbffffff...................
                .....................fffffffffff..................
                ....................fffffffffffff.................
                ....................ffffffffff.ff.................
                ...................fff.fffffff.fff................
                ..................fff..fffffff..ff................
                .................fff...fffffff...ff...............
                .................ff....fffffff...ff...............
                ............ff..fff....fffffff....ff..............
                ...........ff.ffff.....fffffff....fff.............
                ............fffff......fff22ff.....ff.............
                ............fffff......22222ffdb...ff.............
                ...........fffff....22d222d2ff2bb...ff............
                .............f.f..2222221122df2dbb..ff.fff........
                .............f...bb22..222d22b.22ddfffff.f........
                ................bbd1222222222bb..22f2fff..........
                ...............bd222..2222122dbbb..2ffdf..........
                ..............bd22....2.b22..22dbb..f22f..........
                .............dd2.....2bbb.2222222222..222.........
                .............22......2bd222.....2122...22.........
                .............2.......db222.......22.2...2.........
                ....................222.2.........222.............
                ...................222..2..........22.............
                .................22212..............2.............
                .................2................................
                `, SpriteKind.Enemy)
            tiles.placeOnRandomTile(snake, assets.tile`myTile1`)
            snake.follow(playerSprite, 100)
            liserd = sprites.create(img`
                ........................
                ........................
                ...........ccc..........
                ...........cccc.........
                .......ccc..ccccccc.....
                .......cccccc555555cc...
                ........ccb5555555555c..
                .....cc..b555555555555c.
                .....cccb555555ff155555c
                ......cb55555555ff55d55c
                ......b5555555555555555c
                ...cc.b555dd5555bb13bbc.
                ...cccd55ddddd555b3335c.
                .....bdddddddddd55b335c.
                ..cccdddddb55bbddd5555c.
                ..cccdddddb555bbbbcccc..
                ...ccddddddb5555cbcdc...
                ccccbdddddd5cb55cbcc....
                cddddddddd5555ccbbc.....
                .cddddddbdd555bbbcc.....
                ..ccdddbbbdd55cbcdc.....
                ....ccbbcbddddccdddcc...
                ......cccdd555dcccccc...
                ........cccccccc........
                `, SpriteKind.Enemy)
            tiles.placeOnRandomTile(liserd, assets.tile`myTile1`)
            liserd.follow(playerSprite, 90)
        }
    }
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    music.play(music.createSoundEffect(WaveShape.Noise, 735, 936, 255, 255, 500, SoundExpressionEffect.None, InterpolationCurve.Linear), music.PlaybackMode.UntilDone)
    game.setGameOverMessage(false, "You survived " + info.score() + " nights!")
    game.gameOver(false)
})
let liserd: Sprite = null
let snake: Sprite = null
let moonky: Sprite = null
let playerSprite: Sprite = null
let isDaytime = false
music.play(music.createSong(hex`0078000408020200001c00010a006400f401640000040000000000000000000000000005000004180000000400012908000c00012510001400012918001c00012505001c000f0a006400f4010a000004000000000000000000000000000000000212000400080001270c0010000127140018000127`), music.PlaybackMode.InBackground)
game.splash("surviveing camp by kylan", " press A")
info.setScore(0)
let timeSeconds = 0
isDaytime = true
tiles.setCurrentTilemap(tilemap`level2`)
Render.setViewMode(ViewMode.tilemapView)
let mySprite = Render.getRenderSpriteVariable()
playerSprite = sprites.create(assets.image`playerStand`, SpriteKind.Player)
scene.cameraFollowSprite(playerSprite)
tiles.placeOnTile(playerSprite, tiles.getTileLocation(25, 48))
controller.moveSprite(playerSprite, 100, 100)
let statusbar = statusbars.create(20, 4, StatusBarKind.Energy)
statusbar.attachToSprite(playerSprite)
statusbar.setColor(7, 15, 3)
statusbar.setBarBorder(1, 15)
statusbar.max = 500
statusbar.value = 450
setupMapTime()
game.onUpdateInterval(1000, function () {
    timeSeconds += 1
    if (timeSeconds == 20) {
        isDaytime = !(isDaytime)
        timeSeconds = 0
        setupMapTime()
        pause(100)
        color.startFade(color.Black, color.originalPalette)
    }
})
forever(function () {
    if (controller.left.isPressed() || controller.up.isPressed() || (controller.right.isPressed() || controller.down.isPressed())) {
        animation.runImageAnimation(
        playerSprite,
        [img`
            . . . . . . . . . . . . . . . . 
            . . . . . f f f f f f . . . . . 
            . . . . f d d d d d d f . . . . 
            . . . . f d f d d f d f . . . . 
            . . . . f d d d d d d f . . . . 
            . . . . f d d f f d d f . . . . 
            . . . . f d d f f d d f . . . . 
            . . . . . f f f f f f . . . . . 
            . . . . . . f 8 8 f . . . . . . 
            . . . . . f 8 8 8 8 f . . . . . 
            . . . . . f 8 8 8 8 f . . . . . 
            . . . . . f 8 8 8 8 f . . . . . 
            . . . . . f f f f f f . . . . . 
            . . . . . . f . . f . . . . . . 
            . . . . . f f . . f . . . . . . 
            . . . . . . . . . f f . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . f f f f f f . . . . . 
            . . . . f d d d d d d f . . . . 
            . . . . f d f d d f d f . . . . 
            . . . . f d d d d d d f . . . . 
            . . . . f d d f f d d f . . . . 
            . . . . f d d f f d d f . . . . 
            . . . . . f f f f f f . . . . . 
            . . . . . . f 8 8 f . . . . . . 
            . . . . . f 8 8 8 8 f . . . . . 
            . . . . . f 8 8 8 8 f . . . . . 
            . . . . . f 8 8 8 8 f . . . . . 
            . . . . . f f f f f f . . . . . 
            . . . . . . f . . f . . . . . . 
            . . . . . . f . . f f . . . . . 
            . . . . . f f . . . . . . . . . 
            `],
        500,
        true
        )
    } else {
        playerSprite.setImage(assets.image`playerStand`)
    }
    if (controller.A.isPressed() && statusbars.getStatusBarAttachedTo(StatusBarKind.Energy, playerSprite).value > 0) {
        statusbars.getStatusBarAttachedTo(StatusBarKind.Energy, playerSprite).value += -1
        controller.moveSprite(playerSprite, 120, 120)
    } else {
        controller.moveSprite(playerSprite, 90, 90)
    }
})
